### ISSUE TITLE
Provide the Qt wrapper around the low level functions in the exercises 

### ISSUE THREAD

**Issue by dmaier-couchbase** [dmaier-couchbase/cb-workshop-cpp#10]
To learn Qt is not the main focus here so instead the task to implement
- bool Upsert(QString key, QString value)
- bool Upsert(QString key, QJsonObject value)

just let the attendees implement:
- bool Upsert(QString key, QString value)

Also add helper functions to the code those allow the conversion for Qt specific stuff
- char\* <--> QString
  ...

**Comment by tkglaser** [comment]
Done.
